spring.application.name=posts-rest-api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081


# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.accessSeconds=900
app.jwt.cookieName=access_token
app.jwt.issuer=posts-rest-api

logging.level.org.springframework.security=DEBUG
